### ISSUE TITLE
Add support for cm-matchhighlight class

### ISSUE THREAD

**Issue by piotr-cz** [chechnyan/Zenburn#3]
As reported on [bracket-match-highlighter](https://github.com/gintau/bracket-match-highlighter/issues/1) extension and implemented in [themes-for-brackets](https://github.com/Jacse/themes-for-brackets/issues/40).

easiest setup:

``` css
.CodeMirror span.cm-matchhighlight {
    background-color: rgba(255,255,255,.2);
}
```

Reference: [Codemirror: match-highlighter.js addon](http://codemirror.net/doc/manual.html#addon_match-highlighter)
